Fix compilation error with VC++ 2010.  Error is:
C:\MinGW\local\src\bcrypt-ruby\ext\mri\ow-crypt.h(17) : error C4028: formal parameter 1 different from declaration
C:\MinGW\local\src\bcrypt-ruby\ext\mri\ow-crypt.h(17) : error C4028: formal parameter 2 different from declaration
C:\MinGW\local\src\bcrypt-ruby\ext\mri\ow-crypt.h(17) : warning C4273: 'crypt' : inconsistent dll linkage
        c:\mingw\local\ruby\include\ruby-1.9.1\ruby/missing.h(77) : see previous definition of 'crypt'

The fix is to define _CONST as const to match the declaration in missing.h.

Note though that Ruby defines a crypt method in crypt.c.  Is this a problem?